Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-11, with the labels that each got.

#61 Fix Networking.ipAddress webhook's bug
  api/v1alpha1/ironic_webhook.go
Labels: approved, ok-to-test, lgtm, size/S

#54 Clean-up configuration manifests
  Makefile
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/testing/kustomization.yaml
  config/testing/manager_feature_gates_patch.yaml
  test/prepare.sh
Labels: approved, lgtm, size/L

#62 Add Gitignore to ignore compilation tool files
  .gitignore
Labels: size/XS, approved, ok-to-test, lgtm

#66 Fix HA feature gate applied unconditionally
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
Labels: approved, lgtm, size/L

#65 Add an environment file and a configmap to customize the manager
  config/manager/kustomization.yaml
  config/manager/manager.env
  config/manager/manager.yaml
Labels: approved, lgtm, size/S

#69 OWNERS: promote Tuomo to approvers
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#68 :seedling: add PR verifier workflow
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/S

#70 ✨ Rework reporting status to the controller
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
  controllers/ironic_controller.go
  controllers/ironicdatabase_controller.go
  controllers/utils.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/status.go
  pkg/ironic/utils.go
Labels: approved, lgtm, size/L

#73 🐛 Fix invalid names for webhooks
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironicdatabase_webhook.go
  config/webhook/manifests.yaml
Labels: approved, lgtm, size/S

#79 🌱 CI: run `apt update` before installing podman
  .github/workflows/build.yml
Labels: size/XS

#80 🐛 Fix image override in the Makefile, collect more logs
  Makefile
  test/collect-logs.sh
  test/suite_test.go
Labels: approved, lgtm, size/S

#77 ✨ Add basic support for Keepalived
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
  config/crd/bases/metal3.io_ironics.yaml
  main.go
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
  pkg/ironic/version.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#78 :seedling: Change webhook secretName to avoid conflicts
  config/certmanager/certificate.yaml
  config/default/manager_webhook_patch.yaml
Labels: size/XS, approved, lgtm

#83 🐛 Handle surrounding newlines and spaces in user names and passwords
  pkg/ironic/secrets.go
  pkg/ironic/secrets_test.go
Labels: approved, lgtm, size/M
