Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-06, with the labels that each got.

#38 :seedling: bump golang to 1.21.10 and some deps
  Dockerfile
  Makefile
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: lgtm, size/M

#42 Mass-update dependencies
  Dockerfile
  Makefile
  config/crd/bases/metal3.io_ironicdatabases.yaml
  config/crd/bases/metal3.io_ironics.yaml
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/gomod.sh
  test/go.mod
  test/go.sum
Labels: approved, size/L

#44 Add Tuomo to reviewers
  OWNERS_ALIASES
Labels: size/XS
