Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-04, with the labels that each got.

#26 Simplify status conditions (fixes #7)
  README.md
  api/v1alpha1/common.go
  controllers/ironic_controller.go
  controllers/ironicdatabase_controller.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/utils.go
  test/suite_test.go
Labels: size/L

#28 Exercise Ironic in the functional job
  .github/workflows/functional.yml
  test/go.mod
  test/go.sum
  test/kind.yaml
  test/suite_test.go
Labels: approved, lgtm, size/M

#30 🌱 add workflow to approve actions on PR change
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: approved, lgtm, size/M

#33 :sparkles: allow Ironic to set nodeSelector
  api/v1alpha1/ironic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/metal3.io_ironics.yaml
  pkg/ironic/containers.go
Labels: approved, ok-to-test, lgtm, size/S
