Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-12, with the labels that each got.

#82 ⚠️ Rename the API group from metal3.io to ironic
  PROJECT
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironicdatabase_webhook.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ironicdatabases.yaml
  config/crd/patches/cainjection_in_ironics.yaml
  config/crd/patches/webhook_in_ironicdatabases.yaml
  config/crd/patches/webhook_in_ironics.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/v1alpha1_ironic.yaml
  config/samples/v1alpha1_ironicdatabase.yaml
  config/webhook/manifests.yaml
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
Labels: approved, lgtm, size/M

#92 ⚠️ Rework naming of references in the API
  README.md
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
  api/v1alpha1/ironicdatabase_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#95 ✨ Bring back CRD-level image overrides
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironicdatabase_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  internal/controller/ironicdatabase_controller.go
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
  pkg/ironic/database.go
  pkg/ironic/version.go
Labels: approved, lgtm, size/L

#94 :seedling: Add golangci-lint
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Makefile
Labels: approved, lgtm, size/L

#98 ✨ Remove kube-rbac-proxy and use controller run-time provided WithAuthenticationAndAuthorization filter instead
  cmd/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#99 :sparkles: Allows to provide ExtraConfig for Ironic conf
  api/v1alpha1/ironic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
Labels: approved, ok-to-test, lgtm, size/L

#97 ✨ Implement version picker for Ironic
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
  pkg/ironic/database.go
  pkg/ironic/version.go
  pkg/ironic/version_test.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#100 🌱 Add more linters
  .golangci.yaml
  pkg/ironic/database.go
  test/suite_test.go
Labels: approved, lgtm, size/S

#101 🌱 Avoid gocritic warning in the tests
  test/suite_test.go
Labels: approved, lgtm, size/S
