Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-05, with the labels that each got.

#37 add OWNERS_ALIASES support
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#39 explicitly drop pr approver workflow permissions
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: size/XS, approved, lgtm

#36 Modify the "Error info" when ironic is deployed in distributed architecture
  pkg/ironic/ironic.go
Labels: size/XS, approved, ok-to-test, lgtm
