Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-10, with the labels that each got.

#50 :seedling: Add wf to automatically build controller image
  .github/workflows/build-images-action.yml
Labels: approved, lgtm, size/S

#51 bump markdownlint-cli2 to v0.12.0
  hack/markdownlint.sh
Labels: size/XS, approved, lgtm

#53 Update test/prepare.sh to work with podman
  test/prepare.sh
Labels: approved, lgtm, size/M

#57 Rename Distributed to HighAvailability in IronicSpec
  ARCHITECTURE.md
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook.go
  config/crd/bases/metal3.io_ironics.yaml
  pkg/ironic/containers.go
  pkg/ironic/ironic.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#55 bump golang to 1.23.2
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#58 Turn high availability support into a feature gate
  api/v1alpha1/features.go
  api/v1alpha1/ironic_webhook.go
  go.mod
  go.sum
  main.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/M
