Repository metal3-io/ironic-standalone-operator, pull requests merged in 2024-03, with the labels that each got.

#10 Updated docs after the move
  ARCHITECTURE.md
  README.md
Labels: size/XS

#16 Update dependencies, drop unnecessary
  Makefile
  api/v1alpha1/webhook_suite_test.go
  controllers/ironic_controller.go
  controllers/ironicdatabase_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  test/go.mod
  test/go.sum
Labels: size/XL

#17 More logging when reconciling
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/utils.go
Labels: size/M

#18 Bootstrap OWNERS
  OWNERS
Labels: size/XS

#19 Avoid deprecated k8s.io/utils/pointer
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
Labels: size/M

#20 Do not overwrite defaulted fields on the deployments
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/utils.go
  test/functional.sh
  test/suite_test.go
Labels: size/L

#11 Add tests for database and distributed architecture
  .github/workflows/functional.yml
  pkg/ironic/database.go
  test/prepare.sh
  test/suite_test.go
Labels: size/L

#14 Add static test scripts
  Dockerfile
  Makefile
  hack/ensure-go.sh
  hack/gomod.sh
  hack/manifestlint.sh
  hack/markdownlint.sh
Labels: approved, lgtm, size/L

#15 Fix markdownlint issues
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/M

#22 Log collection for the functional job
  .github/workflows/functional.yml
  test/collect-logs.sh
  test/go.mod
  test/prepare.sh
  test/suite_test.go
Labels: approved, lgtm, size/M
