Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-01, with the labels that each got.

#102 🌱 Update dependencies to the latest versions
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/XL

#103 🌱 Correct API version in samples
  config/samples/v1alpha1_ironic.yaml
  config/samples/v1alpha1_ironicdatabase.yaml
Labels: size/XS, approved, lgtm

#104 ✨ Add printcolumns to the kubectl get output
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
Labels: approved, lgtm, size/S

#108 :seedling: bump kubeconform to v0.6.7
  hack/manifestlint.sh
Labels: size/XS, approved, lgtm

#110 🌱 Label pods/deployments with a version and clean up selector labels
  api/v1alpha1/common.go
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
Labels: approved, lgtm, size/M

#113 🌱 Update README, drop ARCHITECTURE
  ARCHITECTURE.md
  README.md
Labels: approved, lgtm, size/L

#112 🌱 CI: implement a test for TLS on Ironic API
  .github/workflows/functional.yml
  test/prepare.sh
  test/suite_test.go
  test/testing.env
Labels: approved, lgtm, size/L

#115 🐛 Update golang.org/x/net to pull the fix for CVE-2024-45338
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#117 🌱 Update Golang version in Dockerfile
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#116 🌱 Promote Adam, Lennart and Riccardo to approvers
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm

#120 :seedling: fix OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: size/XS

#114 🌱 Trivial: shell syntax in test/prepare.sh
  test/prepare.sh
Labels: size/XS, approved, lgtm

#118 🌱 Adapt hack/verify-release.sh from BMO
  hack/verify-release.sh
Labels: approved, lgtm, size/XL

#121 :bug: bump golang to 1.23.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm
