Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-09, with the labels that each got.

#363 ⚠️ Move the JSON RPC port from 8089 to 6189
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  docs/api.md
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
  test/kind.yaml
  test/suite_test.go
Labels: approved, lgtm, size/M

#365 🌱Export IPA_BASEURI to have stable tests in release-0.4
  config/testing/kustomization.yaml
  config/testing/manager_irso_config_patch.yaml
  pkg/ironic/containers.go
Labels: size/XS, approved, lgtm

#362 🌱 Export IPA_BASEURI to have stable tests
  config/testing/kustomization.yaml
  config/testing/manager_irso_config_patch.yaml
  pkg/ironic/containers.go
Labels: size/XS, approved, lgtm

#347 :seedling: switch to new cncf oracle gh runners
  .github/workflows/functional.yml
Labels: size/XS, approved, lgtm

#319 :seedling: switch to new cncf oracle gh runners
  .github/workflows/functional.yml
Labels: size/XS, approved, lgtm

#318 :seedling: switch to new cncf oracle gh runners
  .github/workflows/functional.yml
Labels: size/XS, approved, ok-to-test, lgtm

#371 :seedling: Enable variable shadowing check in govet linter
  .golangci.yaml
  internal/controller/ironic_controller.go
  pkg/ironic/ironic.go
Labels: size/XS, approved, lgtm

#376 :seedling: Fix OSV-Scanner
  .github/workflows/osv-scanner-scan.yml
  .github/workflows/scheduled-osv-scan.yml
Labels: approved, lgtm, size/M

#385 :seedling: remove osv scanner from release branches
  .github/workflows/osv-scanner-scan.yml
Labels: approved, lgtm, size/M

#386 :seedling: add specific time to dependabot config
  .github/dependabot.yml
Labels: approved, lgtm, size/S
