Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-10, with the labels that each got.

#390 :sparkles: Support ironic-image 32.0
  api/v1alpha1/ironic_types.go
  pkg/ironic/validation_test.go
  pkg/ironic/version_test.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#389 :seedling: Add prior art for prepare release
  docs/releasing.md
Labels: size/XS, approved, lgtm

#388 :sparkles: Switch to Ironic 32.0 by default, prepare release-0.6
  Makefile
  config/manager/manager.yaml
  pkg/ironic/version.go
  pkg/ironic/version_test.go
Labels: approved, lgtm, size/S

#394 :rocket: Release v0.5.2
  releasenotes/v0.5.2.md
Labels: approved, lgtm, size/S

#395 :rocket: Release v0.4.1
  releasenotes/v0.4.1.md
Labels: approved, lgtm, size/S

#400 🌱Uplift go 1.24.8 to fix CVEs
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm
