Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-08, with the labels that each got.

#313 🌱 Bump golang to v1.24.5
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#320 :seedling: bump golang to 1.24.6
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#322 :book: Add Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, approved, lgtm

#324 :seedling: bump golang to 1.24.6
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#329 🌱 Tests: increase the timeout in upgrade tests
  test/suite_test.go
Labels: size/XS, approved, lgtm

#328 🌱 Make the CI job run on the local source again
  Makefile
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  docs/releasing.md
Labels: approved, lgtm, size/S

#325 :warning: Update supported versions for ironic-image release-31.0
  api/v1alpha1/ironic_types.go
  pkg/ironic/validation_test.go
  pkg/ironic/version_test.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#331 :sparkles: Prepare release 0.5
  Makefile
  config/manager/manager.yaml
  pkg/ironic/version.go
  pkg/ironic/version_test.go
Labels: approved, lgtm, size/S

#348 :bug: Install kustomize for release workflow
  Makefile
Labels: size/XS, approved, lgtm

#349 :seedling: Tests: increase the node testing timeout for the non-HA case
  test/suite_test.go
Labels: approved, lgtm, size/S

#350 :rocket: Release v0.5.1
  releasenotes/v0.5.1.md
Labels: approved, lgtm, size/S
