Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-02, with the labels that each got.

#122 🌱 Enable functional test to be used on ironic-image/mariadb-image
  test/README.md
  test/suite_test.go
Labels: approved, lgtm, size/L

#123 🌱 Clean-up the functional test scripts
  .github/workflows/functional.yml
  test/README.md
  test/collect-logs.sh
  test/prepare.sh
  test/run.sh
Labels: approved, lgtm, size/M

#127 :seedling: workflows: sync pull_request trigger types
  .github/workflows/build.yml
  .github/workflows/functional.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: approved, lgtm, size/S

#124 🌱 Add a functional test for the ExtraConfig feature
  test/suite_test.go
Labels: approved, lgtm, size/M

#128 :seedling: add dependabot configuration for actions
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#129 🌱 Functional tests: improve versions test, add upgrades
  api/v1alpha1/ironic_types.go
  pkg/ironic/version.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#137 :seedling: pin osv-scanner image in verify-release.sh
  hack/verify-release.sh
Labels: size/XS, approved, lgtm

#138 :warning: Harden the validation around the ironic version
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/version.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  internal/controller/ironic_controller.go
  pkg/ironic/containers_test.go
  pkg/ironic/version.go
  pkg/ironic/version_test.go
Labels: approved, lgtm, size/L

#139 🐛 More precise status message in the Ready condition
  pkg/ironic/ironic.go
  pkg/ironic/status.go
  pkg/ironic/utils.go
Labels: approved, lgtm, size/M

#140 :warning: Finish transition to typed Version
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook_test.go
  api/v1alpha1/version.go
  api/v1alpha1/version_test.go
  cmd/main.go
  internal/controller/ironic_controller.go
  pkg/ironic/containers.go
  pkg/ironic/ironic.go
  pkg/ironic/version.go
  pkg/ironic/version_test.go
Labels: approved, lgtm, size/L
