Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-05, with the labels that each got.

#259 ⚠️ Drop deprecated IronicDatabase API and Ironic.DatabaseName
  .golangci.yaml
  PROJECT
  api/v1alpha1/common.go
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironicdatabase_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ironicdatabases.yaml
  config/crd/patches/webhook_in_ironicdatabases.yaml
  config/rbac/ironicdatabase_editor_role.yaml
  config/rbac/ironicdatabase_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/v1alpha1_ironicdatabase.yaml
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
  internal/controller/utils.go
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/upgrades.go
  pkg/ironic/utils.go
  pkg/ironic/validation.go
  pkg/ironic/validation_test.go
  pkg/ironic/version.go
  test/suite_test.go
Labels: size/XXL, approved, lgtm

#258 ✨ Promote the HighAvailability feature gate to Beta status
  api/v1alpha1/features.go
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
Labels: size/XS, approved, lgtm

#264 :book: add missing SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, lgtm, size/S

#266 :book: add CII badge
  README.md
Labels: size/XS, approved, lgtm
