Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-03, with the labels that each got.

#151 🐛 Fix probes for httpd when the downloader is disabled
  pkg/ironic/containers.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#149 🌱 Store all events in the functional tests
  test/suite_test.go
Labels: approved, lgtm, size/S

#147 :seedling: bump golang to 1.23.7
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#148 :seedling: add go ecosystem to dependabot config
  .github/dependabot.yml
Labels: approved, lgtm, size/S

#161 :seedling: add dependabot workflow
  .github/workflows/dependabot.yml
Labels: approved, lgtm, size/M

#150 🌱 Check the httpd server in the functional tests
  test/suite_test.go
Labels: approved, lgtm, size/M

#166 :seedling: fix dependabot testing issues by re-adding "edited"
  .github/workflows/build.yml
  .github/workflows/functional.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-gh-workflow-approve.yaml
  .github/workflows/pr-verifier.yaml
Labels: size/XS, approved, lgtm

#163 ⚠️ Deprecate the IronicDatabase API and spec.databaseName on Ironic
  .golangci.yaml
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironicdatabase_types.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
Labels: approved, lgtm, size/S

#167 :seedling: bump action/checkout to v4, and pin it
  .github/workflows/build.yml
Labels: size/XS, approved, lgtm

#165 ✨ Support external database connections
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironic_webhook.go
  api/v1alpha1/ironic_webhook_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  internal/controller/ironic_controller.go
  pkg/ironic/containers.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/utils.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#170 :seedling: bump x/net to v0.36.0 and x/oauth2 to v0.28.0
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/S

#171 :seedling: group all github action bumps into single PR
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#175 🌱 Migrate to new style webhooks from controller-runtime 0.17
  .golangci.yaml
  Dockerfile
  api/v1alpha1/ironicdatabase_webhook.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/webhook/manifests.yaml
  internal/webhook/v1alpha1/ironic_webhook.go
  pkg/ironic/containers.go
  pkg/ironic/ironic.go
  pkg/ironic/validation.go
  pkg/ironic/validation_test.go
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#176 🌱 Bump golangci-lint to v1.64.7
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  Makefile
Labels: approved, lgtm, size/S

#180 🌱 Drop unused linter exceptions
  .golangci.yaml
Labels: size/XS, approved, lgtm

#179 🌱 Update controller-runtime and kubernetes dependencies
  Makefile
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/L

#178 ⚠️ Stop defaulting DHCP rangeBegin/rangeEnd
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  config/default/kustomization.yaml
  config/default/webhookcainjection_patch.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  internal/webhook/v1alpha1/ironic_webhook.go
  pkg/ironic/containers.go
  pkg/ironic/validation.go
  pkg/ironic/validation_test.go
  test/suite_test.go
  test/testing.env
Labels: approved, lgtm, size/L

#172 ⚠️ Disallow downgrades when an external database is used
  internal/controller/ironic_controller.go
  test/suite_test.go
Labels: approved, lgtm, size/L

#188 🌱 Functional tests: decrease individual timeouts
  test/suite_test.go
Labels: size/XS, approved, lgtm

#190 🐛 Do not clear the installed version when reconciling
  internal/controller/ironic_controller.go
Labels: size/XS, approved, lgtm

#191 🌱 Extract helpers for database parameters
  pkg/ironic/containers.go
Labels: approved, lgtm, size/L

#193 ⚠️ Drop DisableRPCHostValidation from the API
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  pkg/ironic/containers.go
Labels: approved, lgtm, size/S

#189 🌱 Increase test verbosity, create a junit report
  .github/workflows/functional.yml
  test/run.sh
Labels: approved, lgtm, size/S

#177 :seedling: update osv-scanner to v2.0.0
  .github/workflows/osv-scanner-scan.yml
  hack/verify-release.sh
Labels: approved, lgtm, size/M

#192 🐛 Fix readiness detection for updated daemon sets
  pkg/ironic/utils.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#210 🌱 Dont run golangci-lint separately on internal/controller
  .github/workflows/golangci-lint.yml
  Makefile
Labels: size/XS, approved, lgtm

#213 ✨ Update supported versions for ironic-image release-29.0
  api/v1alpha1/ironic_types.go
  pkg/ironic/validation_test.go
  pkg/ironic/version_test.go
  test/suite_test.go
Labels: approved, lgtm, size/L
