Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-04, with the labels that each got.

#217 🌱 Refactor handling secrets on the controller level
  internal/controller/ironic_controller.go
  internal/controller/utils.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#216 🌱 Enable godot and perfsprint linters
  .golangci.yaml
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/ironic_types.go
  api/v1alpha1/ironicdatabase_types.go
  api/v1alpha1/version.go
  cmd/main.go
  config/crd/bases/ironic.metal3.io_ironicdatabases.yaml
  config/crd/bases/ironic.metal3.io_ironics.yaml
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
  internal/controller/utils.go
  internal/webhook/v1alpha1/ironic_webhook.go
  pkg/ironic/database.go
  pkg/ironic/ironic.go
  pkg/ironic/upgrades.go
  pkg/ironic/utils.go
  pkg/ironic/version.go
  test/suite_test.go
Labels: approved, ok-to-test, lgtm, size/L

#218 🌱 Use minikube as a cluster type in functional tests
  .github/workflows/functional.yml
  test/prepare.sh
  test/testing.env
Labels: approved, lgtm, size/M

#224 :seedling: bump golang to v1.23.8 and x/net to v0.38.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  test/go.mod
  test/go.sum
Labels: approved, lgtm, size/S

#223 :seedling: do not bump major version of github actions
  .github/dependabot.yml
Labels: size/XS, approved, lgtm

#226 🌱 Prepare for multi-node functional tests
  .golangci.yaml
  test/suite_test.go
Labels: approved, lgtm, size/L

#219 🐛 Mount the MariaDB secret when possible
  pkg/ironic/containers.go
  pkg/ironic/upgrades.go
  pkg/ironic/version.go
Labels: approved, lgtm, size/L

#230 ⚠️ Drop support for Ironic 27.0 with HA
  pkg/ironic/ironic.go
  pkg/ironic/secrets.go
  pkg/ironic/secrets_test.go
  pkg/ironic/version.go
Labels: approved, lgtm, size/M

#234 🌱 Tests: log resources when wait was successful
  test/suite_test.go
Labels: size/XS, approved, lgtm

#227 🐛 Make sure the API secret can be updated
  pkg/ironic/containers.go
  pkg/ironic/secrets.go
  pkg/ironic/utils.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#233 🌱 Collect full logs from minikube
  test/collect-logs.sh
Labels: size/XS, approved, lgtm

#238 🌱 Go back to using `minikube image load` with a tarball
  test/prepare.sh
Labels: approved, lgtm, size/S

#237 🐛 Do not requeue while waiting for external events
  internal/controller/ironic_controller.go
  internal/controller/ironicdatabase_controller.go
  internal/controller/utils.go
  pkg/ironic/status.go
Labels: approved, lgtm, size/S

#231 :seedling: add labels to Dockerfile
  Dockerfile
Labels: approved, lgtm, size/S

#240 🌱 Tests: fix the TLS certificate generation for multinode
  test/prepare.sh
Labels: approved, lgtm, size/S

#232 🐛 Do not create conflicting labels on pods and jobs
  api/v1alpha1/common.go
  pkg/ironic/containers.go
  pkg/ironic/ironic.go
  pkg/ironic/upgrades.go
Labels: approved, lgtm, size/S

#241 🌱 Tests: only collect logs from existing containers and IPs from active pods
  test/suite_test.go
Labels: size/XS, approved, lgtm

#239 🐛 Fix detection of a completed Deployment
  pkg/ironic/utils.go
Labels: approved, lgtm, size/S

#195 🌱 Use a multi-node cluster in functional tests
  .github/workflows/functional.yml
  test/run.sh
  test/suite_test.go
Labels: size/XS, approved, lgtm

#236 🌱 Refactoring: group API objects in the new Resources struct
  internal/controller/ironic_controller.go
  pkg/ironic/containers.go
  pkg/ironic/containers_test.go
  pkg/ironic/ironic.go
  pkg/ironic/upgrades.go
  pkg/ironic/utils.go
  pkg/ironic/validation.go
Labels: approved, lgtm, size/L

#244 🌱 Tests: install cert-manager and mariadb-operator using Helm
  test/prepare.sh
Labels: approved, lgtm, size/M

#250 🌱 Separate test on HA with custom TLS and authentication secrets
  test/suite_test.go
Labels: approved, lgtm, size/M

#247 :seedling: Enable unparam linter
  .golangci.yaml
  internal/controller/ironic_controller.go
  internal/controller/utils.go
  pkg/ironic/containers.go
  test/suite_test.go
Labels: approved, ok-to-test, lgtm, size/M

#246 🌱 Tests: verify that the RPC is present and authenticated
  test/suite_test.go
Labels: approved, lgtm, size/M

#249 🐛 Track TLS certificates using an annotation instead of inotify
  pkg/ironic/containers.go
Labels: approved, lgtm, size/S

#221 ✨ Use ReadOnlyRootFileSystem in upgrade jobs
  pkg/ironic/upgrades.go
  pkg/ironic/utils.go
  pkg/ironic/version.go
Labels: approved, lgtm, size/M

#254 ✨ Partial TLS support for JSON RPC
  api/v1alpha1/ironic_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  pkg/ironic/containers.go
  pkg/ironic/validation.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#252 🌱 ReadOnlyRootFileSystem: remove workaround for ironic-image issue
  pkg/ironic/utils.go
Labels: size/XS, approved, lgtm

#256 :seedling: bump golang to 1.24.2
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#257 🌱 Bump Go to 1.24 in hack
  hack/ensure-go.sh
  hack/gomod.sh
Labels: size/XS, approved, lgtm
