Repository metal3-io/ironic-standalone-operator, pull requests merged in 2025-06, with the labels that each got.

#278 :seedling: change functional test to run on larger runner
  .github/workflows/functional.yml
Labels: size/XS, approved, lgtm

#275 🌱 Test: shorten the pod status printed to stdout
  test/suite_test.go
Labels: approved, lgtm, size/S

#279 🌱 Split the functional test into upgrades and regular tests
  .github/workflows/functional.yml
  test/run.sh
  test/suite_test.go
Labels: approved, lgtm, size/M

#287 :seedling: bump golang to 1.24.4
  Dockerfile
  Makefile
Labels: size/XS, approved, lgtm

#286 :seedling: add link checker workflow
  .github/workflows/pr-link-check.yml
  .github/workflows/scheduled-link-check.yml
  docs/api.md
  hack/gen-api-doc.sh
Labels: approved, lgtm, size/M

#288 :seedling: clean up obsolete release variables from Makefile
  Makefile
Labels: size/XS, approved, lgtm

#283 🌱 Enable tagliatelle linter
  .golangci.yaml
  api/v1alpha1/ironic_types.go
  config/crd/bases/ironic.metal3.io_ironics.yaml
  docs/api.md
  pkg/ironic/validation.go
Labels: approved, lgtm, size/S

#289 :sparkles: Update supported versions for ironic-image release-30.0
  api/v1alpha1/ironic_types.go
  pkg/ironic/validation_test.go
  pkg/ironic/version_test.go
  test/suite_test.go
Labels: approved, lgtm, size/M

#295 :seedling: add dependabot config for release-0.4 branch
  .github/dependabot.yml
Labels: approved, lgtm, size/M
